services:
  - type: web
    name: budgettracker-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python manage.py migrate && gunicorn hubSettings.wsgi:application
    plan: free
    autoDeploy: true
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: "True"

  - type: web
    name: budget-frontend
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: serve -s build
    plan: free
    autoDeploy: true
