services:
  - type: web
    name: budgettracker-backend
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: gunicorn hubSettings.wsgi:application
    plan: free
    autoDeploy: true
    envVars:
      - key: DJANGO_SECRET_KEY
        value: 8cw*e7c^fyr4gtb7b*5qxjo+gtw8$6h2j94waxp6j8x=no$toy
      - key: DEBUG
        value: "True"

  - type: web
    name: budget-frontend
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: serve -s build
    plan: free
    autoDeploy: true
